on:
  schedule:
    - cron: '30 */6 * * *'
  push:
    branches:
    - master
name: Update ED report
jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout reffy-reports
      uses: actions/checkout@master
    - name: Checkout reffy
      uses: actions/checkout@master
      with:
        repository: tidoust/reffy
        ref: master
        fetch-depth: 1
        path: reffy
    - name: Test base64 decoding
      run: echo "dG90bw==" | base64 --decode
      working-directory: ../reffy
    - name: Test base64 decoding to a file
      run: |
        echo "dG90bw==" | base64 --decode > test.txt
        cat test.txt
      working-directory: ../reffy
    - name: Setup node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: Install pandoc
      run: sudo apt-get install pandoc
    - name: Retrieve W3C API key
      env:
        CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
      run: echo "$CONFIG_JSON" | base64 --decode > config.json
      working-directory: ../reffy
    - name: Install Reffy's dependencies
      run: npm ci
      working-directory: ../reffy
    - name: Run Reffy's crawler
      run: npm run ed
      working-directory: ../reffy
    - name: Copy reports
      run: rsync -av --exclude=README.md ../reffy/reports/ ./
    - name: Push updates to git
      run: |
        git config user.name "reffy-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add -A
        REFFY_SHA=$(git --git-dir=../reffy/.git rev-parse HEAD)
        git commit -m "Update of ED report from new reffy run" -m "Using reffy commit $REFFY_SHA."
        #npm version patch
        git push origin HEAD:master
        #git push origin --tags
